version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=log-extractor
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data/nodes
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.5.2
    volumes:
      - ./docker/logstash/config:/usr/share/logstash/config
      - ./docker/logstash/pipeline/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
      - ./docker/logstash/pattern:/usr/share/logstash/pattern
    depends_on:
      - elasticsearch
networks:
  default:
    external:
      name: log-extractor